export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const EVENT_REPOSITORY = Symbol('EVENT_REPOSITORY');
export const OUTBOX_STORE = Symbol('OUTBOX_STORE');
export const EVENT_SOURCE_LOOKUP = Symbol('EVENT_SOURCE_LOOKUP');
export const EVENT_TYPE_HANDLER_REGISTRY = Symbol(
  'EVENT_TYPE_HANDLER_REGISTRY',
);
export const TOKEN_SIGNER = Symbol('TOKEN_SIGNER');
export const CORRELATION_ID_PROVIDER = Symbol('CORRELATION_ID_PROVIDER');
export const PROJECTION_STORE = Symbol('PROJECTION_STORE');
export const EVENTS_LIST_READ_STORE = Symbol('EVENTS_LIST_READ_STORE');
export const DAILY_STATS_READ_STORE = Symbol('DAILY_STATS_READ_STORE');
export const TAG_STATS_READ_STORE = Symbol('TAG_STATS_READ_STORE');
export const ROLLUP_STATS_READ_STORE = Symbol('ROLLUP_STATS_READ_STORE');
export const WEEKLY_STATS_READ_STORE = Symbol('WEEKLY_STATS_READ_STORE');
